/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JSlider;

/**
 *
 * @author Julia
 */
public class TlxForm extends javax.swing.JFrame {

    /**
     * Creates new form tlx_form
     */
    public TlxForm() {
        initComponents();
        setChangeListener();
        getSliderLabelList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jSlider3 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jSlider4 = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jSlider7 = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jSlider8 = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Forms/String_values"); // NOI18N
        jButton31.setText(bundle.getString("button_MD")); // NOI18N
        jButton31.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 60, -1));

        jButton32.setText(bundle.getString("button_PD")); // NOI18N
        jButton32.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, -1));

        jButton33.setText(bundle.getString("button_TD")); // NOI18N
        jButton33.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 60, -1));

        jButton34.setText(bundle.getString("button_MD")); // NOI18N
        jButton34.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 60, -1));

        jButton35.setText(bundle.getString("button_OP")); // NOI18N
        jButton35.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 60, -1));

        jButton36.setText(bundle.getString("button_MD")); // NOI18N
        jButton36.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 60, -1));

        jButton37.setText(bundle.getString("button_FR")); // NOI18N
        jButton37.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 60, -1));

        jButton38.setText(bundle.getString("button_MD")); // NOI18N
        jButton38.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 60, -1));

        jButton39.setText(bundle.getString("button_EF")); // NOI18N
        jButton39.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 60, -1));

        jButton40.setText(bundle.getString("button_MD")); // NOI18N
        jButton40.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 60, -1));

        jButton41.setText(bundle.getString("button_TD")); // NOI18N
        jButton41.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 60, -1));

        jButton42.setText(bundle.getString("button_PD")); // NOI18N
        jButton42.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 60, -1));

        jButton43.setText(bundle.getString("button_OP")); // NOI18N
        jButton43.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 60, -1));

        jButton44.setText(bundle.getString("button_PD")); // NOI18N
        jButton44.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 60, -1));

        jButton45.setText(bundle.getString("button_FR")); // NOI18N
        jButton45.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 60, -1));

        jButton46.setText(bundle.getString("button_PD")); // NOI18N
        jButton46.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 60, -1));

        jButton47.setText(bundle.getString("button_EF")); // NOI18N
        jButton47.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 60, -1));

        jButton48.setText(bundle.getString("button_PD")); // NOI18N
        jButton48.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 60, -1));

        jButton49.setText(bundle.getString("button_TD")); // NOI18N
        jButton49.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 60, -1));

        jButton50.setText(bundle.getString("button_OP")); // NOI18N
        jButton50.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 60, -1));

        jButton51.setText(bundle.getString("button_TD")); // NOI18N
        jButton51.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 60, -1));

        jButton52.setText(bundle.getString("button_FR")); // NOI18N
        jButton52.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 60, -1));

        jButton53.setText(bundle.getString("button_TD")); // NOI18N
        jButton53.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 60, -1));

        jButton54.setText(bundle.getString("button_EF")); // NOI18N
        jButton54.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 60, -1));

        jButton55.setText(bundle.getString("button_PD")); // NOI18N
        jButton55.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 60, -1));

        jButton56.setText(bundle.getString("button_FR")); // NOI18N
        jButton56.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 60, -1));

        jButton57.setText(bundle.getString("button_OP")); // NOI18N
        jButton57.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 60, -1));

        jButton58.setText(bundle.getString("button_EF")); // NOI18N
        jButton58.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 60, -1));

        jButton59.setText(bundle.getString("button_EF")); // NOI18N
        jButton59.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 60, -1));

        jButton60.setText(bundle.getString("button_FR")); // NOI18N
        jButton60.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 60, -1));

        jLabel5.setBackground(new java.awt.Color(220, 220, 220));
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 420, 50));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 20, 290));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 20, 290));

        jTabbedPane1.addTab(bundle.getString("tab_compare"), jPanel1); // NOI18N

        jLabel1.setText(bundle.getString("label_MD")); // NOI18N

        jLabel2.setText(bundle.getString("label_PD")); // NOI18N

        jLabel3.setText(bundle.getString("label_TD")); // NOI18N

        jLabel4.setText(bundle.getString("label_OP")); // NOI18N

        jLabel7.setText(bundle.getString("label_EF")); // NOI18N

        jLabel8.setText(bundle.getString("label_FR")); // NOI18N

        jLabel9.setText(bundle.getString("start_state")); // NOI18N

        jLabel10.setText(bundle.getString("start_state")); // NOI18N

        jLabel11.setText(bundle.getString("start_state")); // NOI18N

        jLabel12.setText(bundle.getString("start_state")); // NOI18N

        jLabel13.setText(bundle.getString("start_state")); // NOI18N

        jLabel14.setText(bundle.getString("start_state")); // NOI18N

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSlider8, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab(bundle.getString("tab_question"), jPanel3); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(bundle.getString("tab_analyze"), jPanel4); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName(bundle.getString("tab_compair")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton51ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TlxForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TlxForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TlxForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TlxForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TlxForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider7;
    private javax.swing.JSlider jSlider8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    //private ArrayList[][] sliderList = new ArrayList[5][1];
    
    private void setChangeListener(){
        FormListener listener = FormListener.getInstance(this);
        jSlider1.addChangeListener(listener);
        jSlider2.addChangeListener(listener);
        jSlider3.addChangeListener(listener);
        jSlider4.addChangeListener(listener);
        jSlider7.addChangeListener(listener);
        jSlider8.addChangeListener(listener);
    }
    
    private void getSliderLabelList(){
      
    /*
        sliderList[0][0].add(jSlider1);
        sliderList[0][1].add(jLabel9);
        
        sliderList[0][0].add(jSlider2);
        sliderList[0][1].add(jLabel10);
        
        sliderList[0][0].add(jSlider3);
        sliderList[0][1].add(jLabel12);
        
        sliderList[0][0].add(jSlider4);
        sliderList[0][1].add(jLabel11);
        
        sliderList[0][0].add(jSlider7);
        sliderList[0][1].add(jLabel13);
        
        sliderList[0][0].add(jSlider8);
        sliderList[0][1].add(jLabel14);
    */
    }
    
    public javax.swing.JLabel getSliderLabel(javax.swing.JSlider slider){
        javax.swing.JLabel label = jLabel9;
        
        if(slider == jSlider1){
            label = jLabel9;
        }else if(slider == jSlider2){
            label = jLabel10;
        }else if(slider == jSlider3){
            label = jLabel12;
        }else if(slider == jSlider4){
            label = jLabel11;
        }else if(slider == jSlider7){
            label = jLabel13;
        }else if(slider == jSlider8){
            label = jLabel14;
        }
        
    return label;
    }
    
    public void setLabeltext(javax.swing.JLabel label, String text){
        label.setText(text);
    }
}
