/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import tlx.TLXElement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSlider;

/**
 *
 * @author Julia
 */
public class TLXForm extends javax.swing.JFrame {

    /**
     * Creates new form tlx_form
     */
    public TLXForm() {
        createForm();
    }

    public void createForm(){
        initComponents();
        setChangeListener();
        fillTLXElementList();
        doButtonGroups();
        setAnalysePanelButtons(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jSlider3 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jSlider4 = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jSlider7 = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jSlider8 = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Forms/String_values"); // NOI18N
        jButton31.setText(bundle.getString("button_MD")); // NOI18N
        jButton31.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 60, -1));

        jButton32.setText(bundle.getString("button_PD")); // NOI18N
        jButton32.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, -1));

        jButton33.setText(bundle.getString("button_TD")); // NOI18N
        jButton33.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, -1));

        jButton34.setText(bundle.getString("button_MD")); // NOI18N
        jButton34.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 60, -1));

        jButton35.setText(bundle.getString("button_OP")); // NOI18N
        jButton35.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, -1));

        jButton36.setText(bundle.getString("button_MD")); // NOI18N
        jButton36.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 60, -1));

        jButton37.setText(bundle.getString("button_FR")); // NOI18N
        jButton37.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 60, -1));

        jButton38.setText(bundle.getString("button_MD")); // NOI18N
        jButton38.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 60, -1));

        jButton39.setText(bundle.getString("button_EF")); // NOI18N
        jButton39.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 60, -1));

        jButton40.setText(bundle.getString("button_MD")); // NOI18N
        jButton40.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 60, -1));

        jButton41.setText(bundle.getString("button_TD")); // NOI18N
        jButton41.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 60, -1));

        jButton42.setText(bundle.getString("button_PD")); // NOI18N
        jButton42.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 60, -1));

        jButton43.setText(bundle.getString("button_OP")); // NOI18N
        jButton43.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 60, -1));

        jButton44.setText(bundle.getString("button_PD")); // NOI18N
        jButton44.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 60, -1));

        jButton45.setText(bundle.getString("button_FR")); // NOI18N
        jButton45.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 60, -1));

        jButton46.setText(bundle.getString("button_PD")); // NOI18N
        jButton46.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 60, -1));

        jButton47.setText(bundle.getString("button_EF")); // NOI18N
        jButton47.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 60, -1));

        jButton48.setText(bundle.getString("button_PD")); // NOI18N
        jButton48.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 60, -1));

        jButton49.setText(bundle.getString("button_TD")); // NOI18N
        jButton49.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 60, -1));

        jButton50.setText(bundle.getString("button_OP")); // NOI18N
        jButton50.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 60, -1));

        jButton51.setText(bundle.getString("button_TD")); // NOI18N
        jButton51.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 60, -1));

        jButton52.setText(bundle.getString("button_FR")); // NOI18N
        jButton52.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 60, -1));

        jButton53.setText(bundle.getString("button_TD")); // NOI18N
        jButton53.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 60, -1));

        jButton54.setText(bundle.getString("button_EF")); // NOI18N
        jButton54.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 60, -1));

        jButton55.setText(bundle.getString("button_PD")); // NOI18N
        jButton55.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 60, -1));

        jButton56.setText(bundle.getString("button_FR")); // NOI18N
        jButton56.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 60, -1));

        jButton57.setText(bundle.getString("button_OP")); // NOI18N
        jButton57.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 60, -1));

        jButton58.setText(bundle.getString("button_EF")); // NOI18N
        jButton58.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 60, -1));

        jButton59.setText(bundle.getString("button_EF")); // NOI18N
        jButton59.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 60, -1));

        jButton60.setText(bundle.getString("button_FR")); // NOI18N
        jButton60.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel1.add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 60, -1));

        jLabel5.setBackground(new java.awt.Color(220, 220, 220));
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 420, 50));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 20, 290));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 20, 290));

        jTabbedPane1.addTab(bundle.getString("tab_compare"), jPanel1); // NOI18N
        jPanel1.getAccessibleContext().setAccessibleName(bundle.getString("tab_compare")); // NOI18N

        jLabel1.setText(bundle.getString("label_MD")); // NOI18N

        jLabel2.setText(bundle.getString("label_PD")); // NOI18N

        jLabel3.setText(bundle.getString("label_TD")); // NOI18N

        jLabel4.setText(bundle.getString("label_OP")); // NOI18N

        jLabel7.setText(bundle.getString("label_EF")); // NOI18N

        jLabel8.setText(bundle.getString("label_FR")); // NOI18N

        jLabel9.setText(bundle.getString("start_state")); // NOI18N

        jLabel10.setText(bundle.getString("start_state")); // NOI18N

        jLabel11.setText(bundle.getString("start_state")); // NOI18N

        jLabel12.setText(bundle.getString("start_state")); // NOI18N

        jLabel13.setText(bundle.getString("start_state")); // NOI18N

        jLabel14.setText(bundle.getString("start_state")); // NOI18N

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSlider8, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab(bundle.getString("tab_question"), jPanel3); // NOI18N

        jButton2.setText(bundle.getString("button_NewStart")); // NOI18N

        jButton3.setText(bundle.getString("button_save")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab(bundle.getString("tab_analyze"), jPanel4); // NOI18N

        jButton1.setText(bundle.getString("button_Analyse")); // NOI18N

        jLabel15.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName(bundle.getString("tab_compair")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton51ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TLXForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TLXForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TLXForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TLXForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TLXForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider7;
    private javax.swing.JSlider jSlider8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private List<TLXButtonGroup> buttonGroups = new ArrayList<TLXButtonGroup>();
    private List<TLXElement> tlxElements = new ArrayList<TLXElement>();
    
    private void setChangeListener(){
        SliderListener listener = new SliderListener(tlxElements);
        jSlider1.addChangeListener(listener);
        jSlider2.addChangeListener(listener);
        jSlider3.addChangeListener(listener);
        jSlider4.addChangeListener(listener);
        jSlider7.addChangeListener(listener);
        jSlider8.addChangeListener(listener);
        
        ComparButtonListener buttonListener = new ComparButtonListener(buttonGroups);
        jButton31.addActionListener(buttonListener);
        jButton32.addActionListener(buttonListener);
        jButton33.addActionListener(buttonListener);
        jButton34.addActionListener(buttonListener);
        jButton35.addActionListener(buttonListener);
        jButton36.addActionListener(buttonListener);
        jButton37.addActionListener(buttonListener);
        jButton38.addActionListener(buttonListener);
        jButton39.addActionListener(buttonListener);
        jButton40.addActionListener(buttonListener);
        jButton41.addActionListener(buttonListener);
        jButton42.addActionListener(buttonListener);
        jButton43.addActionListener(buttonListener);
        jButton44.addActionListener(buttonListener);
        jButton45.addActionListener(buttonListener);
        jButton46.addActionListener(buttonListener);
        jButton47.addActionListener(buttonListener);
        jButton48.addActionListener(buttonListener);
        jButton49.addActionListener(buttonListener);
        jButton50.addActionListener(buttonListener);
        jButton51.addActionListener(buttonListener);
        jButton52.addActionListener(buttonListener);
        jButton53.addActionListener(buttonListener);
        jButton54.addActionListener(buttonListener);
        jButton55.addActionListener(buttonListener);
        jButton56.addActionListener(buttonListener);
        jButton57.addActionListener(buttonListener);
        jButton58.addActionListener(buttonListener);
        jButton59.addActionListener(buttonListener);
        jButton60.addActionListener(buttonListener);
        
        AnalyseButtonListener aButtonListener = new AnalyseButtonListener(this, buttonGroups, tlxElements);
        jButton1.addActionListener(aButtonListener);
        
        NewStartButtonListener nButtonListener = new NewStartButtonListener(this);
        jButton2.addActionListener(nButtonListener);
        
        SaveButtonListener sButtonListener = new SaveButtonListener(tlxElements);
        jButton3.addActionListener(sButtonListener);
    }
    
    private void fillTLXElementList(){
        /*
        the List contains all TLXElements
        the TLXElements keeps all Formeelements of each part together
        */
        TLXElement md = new TLXElement(jSlider1, jLabel9, "md", "mental_demand");
        TLXElement pd = new TLXElement(jSlider2, jLabel10, "pd", "physical_demand");
        TLXElement td = new TLXElement(jSlider3, jLabel12, "td", "temporal_demand");
        TLXElement op = new TLXElement(jSlider4, jLabel11, "op", "performance");
        TLXElement ef = new TLXElement(jSlider7, jLabel13, "ef", "effort");
        TLXElement fr = new TLXElement(jSlider8, jLabel14, "fr", "frustration");
        
        tlxElements.add(md);
        tlxElements.add(pd);
        tlxElements.add(td);
        tlxElements.add(op);
        tlxElements.add(ef);
        tlxElements.add(fr);
    }  
    
    private void doButtonGroups(){
        /*
        contains all 2-pair-Button-Groups for the "Pair-wise comparisons"-Panal
        thats importent that the user can only chouse one button of each group
        */
        TLXButtonGroup group11 = new TLXButtonGroup(jButton31, jButton32);
        TLXButtonGroup group12 = new TLXButtonGroup(jButton33, jButton34);
        TLXButtonGroup group13 = new TLXButtonGroup(jButton35, jButton36);
        TLXButtonGroup group14 = new TLXButtonGroup(jButton37, jButton38);
        TLXButtonGroup group15 = new TLXButtonGroup(jButton39, jButton40);
        
        TLXButtonGroup group21 = new TLXButtonGroup(jButton41, jButton42);
        TLXButtonGroup group22 = new TLXButtonGroup(jButton43, jButton44);
        TLXButtonGroup group23 = new TLXButtonGroup(jButton45, jButton46);
        TLXButtonGroup group24 = new TLXButtonGroup(jButton47, jButton48);
        TLXButtonGroup group25 = new TLXButtonGroup(jButton49, jButton50);
        
        TLXButtonGroup group31 = new TLXButtonGroup(jButton51, jButton52);
        TLXButtonGroup group32 = new TLXButtonGroup(jButton53, jButton54);
        TLXButtonGroup group33 = new TLXButtonGroup(jButton55, jButton56);
        TLXButtonGroup group34 = new TLXButtonGroup(jButton57, jButton58);
        TLXButtonGroup group35 = new TLXButtonGroup(jButton59, jButton60);

        buttonGroups.add(group11);
        buttonGroups.add(group12);
        buttonGroups.add(group13);
        buttonGroups.add(group14);
        buttonGroups.add(group15);
        
        buttonGroups.add(group21);
        buttonGroups.add(group22);
        buttonGroups.add(group23);
        buttonGroups.add(group24);
        buttonGroups.add(group25);
        
        buttonGroups.add(group31);
        buttonGroups.add(group32);
        buttonGroups.add(group33);
        buttonGroups.add(group34);
        buttonGroups.add(group35);
    }
    
    public void setAttentionLabelText(String text){
        jLabel15.setText(text);
    }
          
    public void setAnalysePanelButtons(boolean visibility){
        jButton3.setEnabled(visibility);
        jButton2.setEnabled(visibility);
    }
}
